Gemfile:
  optional:
    ":development":
      - gem: "pry"
      - gem: "pry-byebug"
      - gem: "rspec-wait"
      # - gem: "bolt"
      #   version: "<= 1.48.0"
spec/spec_helper.rb:
  mock_with: ":rspec"

".travis.yml":
  deploy_to_forge:
    enabled: false
  ruby_versions:
    # - 2.5.7
  includes:
    - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=spec
      # rvm: 2.5.7
      stage: spec
    - before_script:
        - bundle exec rake 'litmus:provision_list[docker]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
